// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchExportReports(arg1:Array<string>,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function DeleteReport(arg1:string):Promise<void>;

export function ExportToCSV(arg1:string):Promise<string>;

export function ExportToPDF(arg1:string):Promise<string>;

export function FilterReportData(arg1:string,arg2:Record<string, string>):Promise<Record<string, any>>;

export function GenerateReport(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function GetAPISettings():Promise<Record<string, string>>;

export function GetReportCategories():Promise<Array<string>>;

export function GetReportConfig():Promise<Record<string, any>>;

export function GetReportHistory():Promise<Array<Record<string, any>>>;

export function GetSupportedReportTypes():Promise<Array<Record<string, string>>>;

export function Greet(arg1:string):Promise<string>;

export function ListReports():Promise<Array<Record<string, string>>>;

export function OpenReport(arg1:string):Promise<void>;

export function SaveAPISettings(arg1:string,arg2:string):Promise<boolean>;

export function ScheduleReport(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function SearchAllReports(arg1:string):Promise<Record<string, any>>;

export function SetReportConfig(arg1:number,arg2:string):Promise<boolean>;

export function TestAPIConnection():Promise<Record<string, any>>;
