// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchExportReports(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BatchExportReports'](arg1, arg2, arg3, arg4);
}

export function DeleteReport(arg1) {
  return window['go']['main']['App']['DeleteReport'](arg1);
}

export function ExportToCSV(arg1) {
  return window['go']['main']['App']['ExportToCSV'](arg1);
}

export function ExportToPDF(arg1) {
  return window['go']['main']['App']['ExportToPDF'](arg1);
}

export function FilterReportData(arg1, arg2) {
  return window['go']['main']['App']['FilterReportData'](arg1, arg2);
}

export function GenerateReport(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateReport'](arg1, arg2, arg3);
}

export function GetAPISettings() {
  return window['go']['main']['App']['GetAPISettings']();
}

export function GetReportCategories() {
  return window['go']['main']['App']['GetReportCategories']();
}

export function GetReportConfig() {
  return window['go']['main']['App']['GetReportConfig']();
}

export function GetReportHistory() {
  return window['go']['main']['App']['GetReportHistory']();
}

export function GetSupportedReportTypes() {
  return window['go']['main']['App']['GetSupportedReportTypes']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListReports() {
  return window['go']['main']['App']['ListReports']();
}

export function OpenReport(arg1) {
  return window['go']['main']['App']['OpenReport'](arg1);
}

export function SaveAPISettings(arg1, arg2) {
  return window['go']['main']['App']['SaveAPISettings'](arg1, arg2);
}

export function ScheduleReport(arg1, arg2, arg3) {
  return window['go']['main']['App']['ScheduleReport'](arg1, arg2, arg3);
}

export function SearchAllReports(arg1) {
  return window['go']['main']['App']['SearchAllReports'](arg1);
}

export function SetReportConfig(arg1, arg2) {
  return window['go']['main']['App']['SetReportConfig'](arg1, arg2);
}

export function TestAPIConnection() {
  return window['go']['main']['App']['TestAPIConnection']();
}
